### ISSUE TITLE
cannot download paid apps

### ISSUE THREAD

**Issue by zhicai** [egirault/googleplay-api#17]
hi,
   i got the following error when trying downloading paid app from google play store:

Traceback (most recent call last):
  File "download.py", line 43, in <module>
    data = api.download(packagename, vc, ot)
  File "/home/zxia10x/free/googleplay.py", line 261, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
  File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 64, in **getitem**
    return self._values[key]
IndexError: list index out of range

it seems that the the format of messages are different between paid and free.

so, would you please fix it?
thanks

**Comment by nikaro** [comment]
Same issue, I can't download paid apps that I bought on Google Play Store.

**Comment by jeffhiltz** [comment]
I see the same error trying to download a free app.  Another user has seen it while searching.  See issue #23.

**Comment by nikaro** [comment]
@jeffhiltz with free apps I had this issue too, but it was my ANDROIDID which was bad. May be you need to check it.

**Comment by jeffhiltz** [comment]
@NiKaro127 Most of the downloads I've tried work, it's just the odd one that fails so I think the ANDROIDID is okay.  Thanks for the idea.
