### ISSUE TITLE
Bug in categories.py

### ISSUE THREAD

**Issue by virtualabs** [egirault/googleplay-api#2]
Categories.py seems non-working anymore, issuing HTTP 500 error (oO)

Traceback (most recent call last):
  File "categories.py", line 15, in <module>
    response = api.browse()
  File "/home/virtualabs/playstore/googleplay-api/googleplay.py", line 209, in browse
    message = self.executeRequestApi2(path)
  File "/home/virtualabs/playstore/googleplay-api/googleplay.py", line 165, in executeRequestApi2
    data = urllib2.urlopen(request).read()
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

Launched from my laptop connected to the Internet through my phone.

**Comment by Fuzion24** [comment]
Seems to work fine for me, is this related to your other androidID issue?

**Comment by virtualabs** [comment]
Yep, too. Please close my 2 issues. I mistyped my androidID.

**Comment by Fuzion24** [comment]
I have nothing to do with this project, but I think you can close the issue yourself..

**Comment by Fuzion24** [comment]
Actually, it might be nice if the library somehow regex'ed the AndroidID and failed if it was invalid...
