### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by Artgit** [egirault/googleplay-api#23]
hello, I'm try to use this API but each time after command "python search.py 'angry'" receive error:

Title;Package name;Creator;Super Dev;Price;Offer Type;Version Code;Size;Rating;Num Downloads
Traceback (most recent call last):
File "search.py", line 41, in 
doc = message.doc[0]
File "build\bdist.win32\egg\google\protobuf\internal\containers.py", line 64, in getitem
IndexError: list index out of range

Could you please help me with it ?

**Comment by JosephRedfern** [comment]
I have the same issue - did you get anywhere with this?

**Comment by Artgit** [comment]
@JosephRedfern , no and I have moved to this lib https://github.com/Akdeniz/google-play-crawler

**Comment by JosephRedfern** [comment]
@Artgit I'll take a look - thanks.

**Comment by djhacktor** [comment]
@JosephRedfern  have you got any success on this issue ?

**Comment by jeffhiltz** [comment]
I'm seeing the same thing while downloading.  It only happens sometimes; much of the time I'm able to download the APK file successfully.

I'm using login/pass/androidId with AUTH_TOKEN = None.

```
  File "/home/fetcher/asknice/python_api/googleplay.py", line 267, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

**Comment by jophde** [comment]
I used an APID from a device that's not synced with developer account and it worked.
