### ISSUE TITLE
It can not working for me 

### ISSUE THREAD

**Issue by hfeeki** [egirault/googleplay-api#41]
Next is the error info: 

```
googleplay-api michael$ python search.py earth
Title;Package name;Creator;Super Dev;Price;Offer Type;Version Code;Size;Rating;Num Downloads
Traceback (most recent call last):
  File "search.py", line 39, in <module>
    doc = message.doc[0]
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 64, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

the message.doc == []

**Comment by nguyenvulong** [comment]
try another android-id
remember one thing: android id must be used together with Google account (email + password)
You can get one by following this codekiem.com/2014/08/07/official-apk-downloader-v2-download-apk-files-from-google-play-store-to-pc/

Android phone is needed.
