### ISSUE TITLE
Some apps are not downloading- IndexError: list index out of range

### ISSUE THREAD

**Issue by avikmrr** [egirault/googleplay-api#78]
Package Name: com.philips.lighting.hue2
Downloading 0.0bytes... commands {
  displayErrorMessage: "Your device is not compatible with this item."
}

Traceback (most recent call last):
  File "download.py", line 47, in <module>
    data = api.download(packagename, vc, ot)
  File "/Users/avinash.af.kumar/googleplay_client/googleplay.py", line 279, in download
    cookie = message.payload.buyResponse.purchaseStatusResponse.appDeliveryData.downloadAuthCookie[0]
  File "/Users/avinash.af.kumar/DSTENV/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range

> Although my device is compatible with the app, I am having trouble downloading some apps?
Can anyone tell me the reason?

**Comment by 4knahs** [comment]
"Your device is not compatible with this item."

Your list is probably empty?

**Comment by Gudui** [comment]
Experincing same problem, help.

**Comment by 4knahs** [comment]
Well other than adding a check to see if the returned list is empty, try changing your device UA in `googleplay.py` to something more recent. E.g.:

```

            headers = { "Accept-Language": self.lang,
                                    "Authorization": "GoogleLogin auth=%s" % self.authSubToken,
                                    "X-DFE-Enabled-Experiments": "cl:billing.select_add_instrument_by_default",
                                    "X-DFE-Unsupported-Experiments": "nocache:billing.use_charging_poller,market_emails,buyer_currency,prod_baseline,checkin.set_asset_paid_app_field,shekel_test,content_ratings,buyer_currency_in_app,nocache:encrypted_apk,recent_changes",
                                    "X-DFE-Device-Id": self.androidId,
                                    "X-DFE-Client-Id": "am-android-google",
                                    #"X-DFE-Logging-Id": self.loggingId2, # Deprecated?
                                    # "User-Agent": "Android-Finsky/4.4.3 (api=3,versionCode=8016014,sdk=22,device=GT-I9300,hardware=aries,product=GT-I9300)",
                                    "User-Agent": "Android-Finsky/4.4.3 (api=3,versionCode=8016014,sdk=22,device=hammerhead,hardware=hammerhead,product=hammerhead)",
                                    # "User-Agent": "Android-Finsky/3.7.13 (api=3,versionCode=8013013,sdk=22,device=crespo,hardware=herring,product=soju)",
                                    "X-DFE-SmallestScreenWidthDp": "335",
                                    "X-DFE-Filter-Level": "3",
                                    "Accept-Encoding": "",
                                    "Host": "android.clients.google.com"}
```

**Comment by avikmrr** [comment]
@4knahs : Thanks. It actually worked.
